name: CI-reusable_workflow
on: [workflow_call]
jobs:
  CI_Steps:
    runs-on: [self-hosted]
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - run: echo ok
        name: Code Build
      - run: echo ok
        name: Code Test
      - run: echo ok
        name: Code Review
      - run: echo ok
        name: Release Software



