name: Release-reusable_workflow
on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      release_archive_files:
        required: true
        type: string
      npm_install:
        required: true
        type: boolean
jobs:
  CI_Steps:
    runs-on: [self-hosted]
    steps:
      - name: code checkout
        uses: actions/checkout@v4


      -  run: echo npm install
         name: Install nodejs modules
         if: ${{ inputs.npm_install }}

      - name: Import vault token
        id: vault-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.shujadevops.shop:8200
          token: ${{ secrets.vault_token }}
          tlsSkipVerify: true
          secrets: |
            common/data/common  artifactory_user | artifactory_user ;
            common/data/common artifactory_password | artifactory_password ;

      - run: zip -r ${GITHUB_REF}.zip ${{ inputs.release_archive_files }}
        name: prepare artifact
      - run: ls -l
      - run: env

#      - run: curl -v --user ${{ steps.vault-secrets.outputs.artifactory_user }}:${{ steps.vault-secrets.outputs.artifactory_password }} --data-binary @${GITHUB_REF}.zip -X PUT "http://artifactory-internal.shujadevops.shop:8081/artifactory/expense-backend/${GITHUB_REF}.zip"
        name: Release Software

#        if: ${{ startsWith(github.ref, 'refs/tags/') }}



